services:
  web:
    build:
      context: ./src/web
    container_name: ${CLUB_PREFIX}_app
    ports:
      - 8080:80
    networks:
      - app_net

  api:
    build:
      context: ./src/api
    container_name: ${CLUB_PREFIX}_api
    ports:
      - 3000:3000
    networks:
      - app_net
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_PORT: ${DB_PORT}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

  db:
    build:
      context: ./src/db
      args:
        ENVIRONMENT: ${ENVIRONMENT:-development}
    container_name: ${CLUB_PREFIX}_db
    ports:
      - 3307:3306
    networks:
      - app_net
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF-8

volumes:
  db_data:

networks:
  app_net:
    driver: bridge