#!/bin/bash
set -e

DB_USER="${DB_USER:?DB_USER must be set}"
DB_PASSWORD="${DB_PASSWORD:?DB_PASSWORD must be set}"
DB_NAME="${MYSQL_DATABASE:?MYSQL_DATABASE must be set}"

mysql -u root -p"$MYSQL_ROOT_PASSWORD" <<EOSQL
DROP USER IF EXISTS '$DB_USER'@'%';
CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$DB_USER'@'%';
FLUSH PRIVILEGES;
EOSQL