server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    # Try to serve file or directory, fallback to index.html for Angular routing
    try_files $uri $uri/ /index.html;
  }

  # Optional: Cache-Control for static files
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
    expires 1y;
    access_log off;
    log_not_found off;
  }
}